development:
  host: localhost
  adapter: mysql2
  database: nearest_cab 
  username: root
  password: 

test:
  host: localhost
  adapter: mysql2
  database: nearest_cab
  username: root
  password:
